In [9]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
hiv_df = pd.read_csv("hiv_global_timeseries.csv")

In [7]:
hiv_cog = hiv_df[hiv_df["country_code"]=='COG']
hiv_cog.head()

,country_code,country_name,year,indicator,indicator_code,value,unit,age_group,sex,source_org,source_dataset,retrieval_date,notes
560,COG,Congo,2010,Antiretroviral therapy coverage among people l...,PERCENT_PLWH,8.46081,percent,0-14,both,UNAIDS,"AIDSinfo Estimates 2026 (bulk CSV, Area Level ...",2026-08-24,NaN
561,COG,Congo,2011,Antiretroviral therapy coverage among people l...,PERCENT_PLWH,9.21805,percent,0-14,both,UNAIDS,"AIDSinfo Estimates 2026 (bulk CSV, Area Level ...",2026-08-24,NaN
562,COG,Congo,2012,Antiretroviral therapy coverage among people l...,PERCENT_PLWH,10.04775,percent,0-14,both,UNAIDS,"AIDSinfo Estimates 2026 (bulk CSV, Area Level ...",2026-08-24,NaN
563,COG,Congo,2013,Antiretroviral therapy coverage among people l...,PERCENT_PLWH,10.26403,percent,0-14,both,UNAIDS,"AIDSinfo Estimates 2026 (bulk CSV, Area Level ...",2026-08-24,NaN
564,COG,Congo,2014,Antiretroviral therapy coverage among people l...,PERCENT_PLWH,12.71248,percent,0-14,both,UNAIDS,"AIDSinfo Estimates 2026 (bulk CSV, Area Level ...",2026-08-24,NaN

In [11]:
print(hiv_cog.dtypes)
print(f"{hiv_cog.shape[0]} lignes et {hiv_cog.shape[1]} colonnes")

country_code       object
country_name       object
year                int64
indicator          object
indicator_code     object
value             float64
unit               object
age_group          object
sex                object
source_org         object
source_dataset     object
retrieval_date     object
notes              object
dtype: object
1617 lignes et 13 colonnes

In [12]:
hiv_cog = hiv_cog.drop(columns=["notes"])
hiv_cog['retrieval_date'] = pd.to_datetime(hiv_cog['retrieval_date'])
print(hiv_cog.dtypes)

country_code              object
country_name              object
year                       int64
indicator                 object
indicator_code            object
value                    float64
unit                      object
age_group                 object
sex                       object
source_org                object
source_dataset            object
retrieval_date    datetime64[ns]
dtype: object

In [15]:
print(f"\n{hiv_cog.isnull().sum()}")
print(f"{hiv_cog.duplicated().sum()}")

country_code       0
country_name       0
year               0
indicator          0
indicator_code     0
value             57
unit               0
age_group          0
sex                0
source_org         0
source_dataset     0
retrieval_date     0
dtype: int64
9

In [18]:
display(hiv_cog[hiv_cog.duplicated(keep=False)])

,country_code,country_name,year,indicator,indicator_code,value,unit,age_group,sex,source_org,source_dataset,retrieval_date
67202,COG,Congo,2022,HIV tests performed where results were receive...,HIV_0000000027,NaN,count,all,both,WHO,Global Health Observatory (GHO) OData API,2026-08-24
67203,COG,Congo,2022,HIV tests performed where results were receive...,HIV_0000000027,NaN,count,all,both,WHO,Global Health Observatory (GHO) OData API,2026-08-24
67204,COG,Congo,2022,HIV tests performed where results were receive...,HIV_0000000027,NaN,count,all,both,WHO,Global Health Observatory (GHO) OData API,2026-08-24
67205,COG,Congo,2022,HIV tests performed where results were receive...,HIV_0000000027,NaN,count,all,both,WHO,Global Health Observatory (GHO) OData API,2026-08-24
67206,COG,Congo,2023,HIV tests performed where results were receive...,HIV_0000000027,NaN,count,all,both,WHO,Global Health Observatory (GHO) OData API,2026-08-24
67207,COG,Congo,2023,HIV tests performed where results were receive...,HIV_0000000027,NaN,count,all,both,WHO,Global Health Observatory (GHO) OData API,2026-08-24
67208,COG,Congo,2023,HIV tests performed where results were receive...,HIV_0000000027,NaN,count,all,both,WHO,Global Health Observatory (GHO) OData API,2026-08-24
67209,COG,Congo,2023,HIV tests performed where results were receive...,HIV_0000000027,NaN,count,all,both,WHO,Global Health Observatory (GHO) OData API,2026-08-24
67210,COG,Congo,2024,HIV tests performed where results were receive...,HIV_0000000027,NaN,count,all,both,WHO,Global Health Observatory (GHO) OData API,2026-08-24
67211,COG,Congo,2024,HIV tests performed where results were receive...,HIV_0000000027,NaN,count,all,both,WHO,Global Health Observatory (GHO) OData API,2026-08-24
67212,COG,Congo,2024,HIV tests performed where results were receive...,HIV_0000000027,NaN,count,all,both,WHO,Global Health Observatory (GHO) OData API,2026-08-24
67213,COG,Congo,2024,HIV tests performed where results were receive...,HIV_0000000027,NaN,count,all,both,WHO,Global Health Observatory (GHO) OData API,2026-08-24

In [20]:
# ==================================================
# Suppressions des doublons
# ==================================================
hiv_cog = hiv_cog.drop_duplicates()
hiv_cog = hiv_cog.reset_index(drop=True)
hiv_cog.duplicated().sum()

np.int64(0)

In [21]:
# ==================================================
# Gestion des valeurs manquantes
# ==================================================

# Isolation des valeurs manquantes
missing_values_df = hiv_cog[hiv_cog['value'].isna()]
display(missing_values_df)

,country_code,country_name,year,indicator,indicator_code,value,unit,age_group,sex,source_org,source_dataset,retrieval_date
438,COG,Congo,2022,HIV tests performed where results were receive...,HIV_0000000027,NaN,count,all,both,WHO,Global Health Observatory (GHO) OData API,2026-08-24
439,COG,Congo,2023,HIV tests performed where results were receive...,HIV_0000000027,NaN,count,all,both,WHO,Global Health Observatory (GHO) OData API,2026-08-24
440,COG,Congo,2024,HIV tests performed where results were receive...,HIV_0000000027,NaN,count,all,both,WHO,Global Health Observatory (GHO) OData API,2026-08-24
1166,COG,Congo,2017,People living with HIV who have suppressed vir...,VIRAL_LOAD_SUPPRESSION,NaN,percent,0-14,both,UNAIDS,"AIDSinfo Estimates 2026 (bulk CSV, Area Level ...",2026-08-24
1167,COG,Congo,2018,People living with HIV who have suppressed vir...,VIRAL_LOAD_SUPPRESSION,NaN,percent,0-14,both,UNAIDS,"AIDSinfo Estimates 2026 (bulk CSV, Area Level ...",2026-08-24
1168,COG,Congo,2019,People living with HIV who have suppressed vir...,VIRAL_LOAD_SUPPRESSION,NaN,percent,0-14,both,UNAIDS,"AIDSinfo Estimates 2026 (bulk CSV, Area Level ...",2026-08-24
1169,COG,Congo,2020,People living with HIV who have suppressed vir...,VIRAL_LOAD_SUPPRESSION,NaN,percent,0-14,both,UNAIDS,"AIDSinfo Estimates 2026 (bulk CSV, Area Level ...",2026-08-24
1170,COG,Congo,2021,People living with HIV who have suppressed vir...,VIRAL_LOAD_SUPPRESSION,NaN,percent,0-14,both,UNAIDS,"AIDSinfo Estimates 2026 (bulk CSV, Area Level ...",2026-08-24
1171,COG,Congo,2022,People living with HIV who have suppressed vir...,VIRAL_LOAD_SUPPRESSION,NaN,percent,0-14,both,UNAIDS,"AIDSinfo Estimates 2026 (bulk CSV, Area Level ...",2026-08-24
1172,COG,Congo,2023,People living with HIV who have suppressed vir...,VIRAL_LOAD_SUPPRESSION,NaN,percent,0-14,both,UNAIDS,"AIDSinfo Estimates 2026 (bulk CSV, Area Level ...",2026-08-24
1173,COG,Congo,2024,People living with HIV who have suppressed vir...,VIRAL_LOAD_SUPPRESSION,NaN,percent,0-14,both,UNAIDS,"AIDSinfo Estimates 2026 (bulk CSV, Area Level ...",2026-08-24
1174,COG,Congo,2025,People living with HIV who have suppressed vir...,VIRAL_LOAD_SUPPRESSION,NaN,percent,0-14,both,UNAIDS,"AIDSinfo Estimates 2026 (bulk CSV, Area Level ...",2026-08-24
1175,COG,Congo,2017,People living with HIV who have suppressed vir...,VIRAL_LOAD_SUPPRESSION,NaN,percent,15+,both,UNAIDS,"AIDSinfo Estimates 2026 (bulk CSV, Area Level ...",2026-08-24
1176,COG,Congo,2018,People living with HIV who have suppressed vir...,VIRAL_LOAD_SUPPRESSION,NaN,percent,15+,both,UNAIDS,"AIDSinfo Estimates 2026 (bulk CSV, Area Level ...",2026-08-24
1177,COG,Congo,2019,People living with HIV who have suppressed vir...,VIRAL_LOAD_SUPPRESSION,NaN,percent,15+,both,UNAIDS,"AIDSinfo Estimates 2026 (bulk CSV, Area Level ...",2026-08-24
1178,COG,Congo,2020,People living with HIV who have suppressed vir...,VIRAL_LOAD_SUPPRESSION,NaN,percent,15+,both,UNAIDS,"AIDSinfo Estimates 2026 (bulk CSV, Area Level ...",2026-08-24
1179,COG,Congo,2021,People living with HIV who have suppressed vir...,VIRAL_LOAD_SUPPRESSION,NaN,percent,15+,both,UNAIDS,"AIDSinfo Estimates 2026 (bulk CSV, Area Level ...",2026-08-24
1180,COG,Congo,2022,People living with HIV who have suppressed vir...,VIRAL_LOAD_SUPPRESSION,NaN,percent,15+,both,UNAIDS,"AIDSinfo Estimates 2026 (bulk CSV, Area Level ...",2026-08-24
1181,COG,Congo,2023,People living with HIV who have suppressed vir...,VIRAL_LOAD_SUPPRESSION,NaN,percent,15+,both,UNAIDS,"AIDSinfo Estimates 2026 (bulk CSV, Area Level ...",2026-08-24
1182,COG,Congo,2024,People living with HIV who have suppressed vir...,VIRAL_LOAD_SUPPRESSION,NaN,percent,15+,both,UNAIDS,"AIDSinfo Estimates 2026 (bulk CSV, Area Level ...",2026-08-24
1183,COG,Congo,2025,People living with HIV who have suppressed vir...,VIRAL_LOAD_SUPPRESSION,NaN,percent,15+,both,UNAIDS,"AIDSinfo Estimates 2026 (bulk CSV, Area Level ...",2026-08-24
1184,COG,Congo,2017,People living with HIV who have suppressed vir...,VIRAL_LOAD_SUPPRESSION,NaN,percent,15+,female,UNAIDS,"AIDSinfo Estimates 2026 (bulk CSV, Area Level ...",2026-08-24
1185,COG,Congo,2018,People living with HIV who have suppressed vir...,VIRAL_LOAD_SUPPRESSION,NaN,percent,15+,female,UNAIDS,"AIDSinfo Estimates 2026 (bulk CSV, Area Level ...",2026-08-24
1186,COG,Congo,2019,People living with HIV who have suppressed vir...,VIRAL_LOAD_SUPPRESSION,NaN,percent,15+,female,UNAIDS,"AIDSinfo Estimates 2026 (bulk CSV, Area Level ...",2026-08-24
1187,COG,Congo,2020,People living with HIV who have suppressed vir...,VIRAL_LOAD_SUPPRESSION,NaN,percent,15+,female,UNAIDS,"AIDSinfo Estimates 2026 (bulk CSV, Area Level ...",2026-08-24
1188,COG,Congo,2021,People living with HIV who have suppressed vir...,VIRAL_LOAD_SUPPRESSION,NaN,percent,15+,female,UNAIDS,"AIDSinfo Estimates 2026 (bulk CSV, Area Level ...",2026-08-24
1189,COG,Congo,2022,People living with HIV who have suppressed vir...,VIRAL_LOAD_SUPPRESSION,NaN,percent,15+,female,UNAIDS,"AIDSinfo Estimates 2026 (bulk CSV, Area Level ...",2026-08-24
1190,COG,Congo,2023,People living with HIV who have suppressed vir...,VIRAL_LOAD_SUPPRESSION,NaN,percent,15+,female,UNAIDS,"AIDSinfo Estimates 2026 (bulk CSV, Area Level ...",2026-08-24
1191,COG,Congo,2024,People living with HIV who have suppressed vir...,VIRAL_LOAD_SUPPRESSION,NaN,percent,15+,female,UNAIDS,"AIDSinfo Estimates 2026 (bulk CSV, Area Level ...",2026-08-24
1192,COG,Congo,2025,People living with HIV who have suppressed vir...,VIRAL_LOAD_SUPPRESSION,NaN,percent,15+,female,UNAIDS,"AIDSinfo Estimates 2026 (bulk CSV, Area Level ...",2026-08-24
1193,COG,Congo,2017,People living with HIV who have suppressed vir...,VIRAL_LOAD_SUPPRESSION,NaN,percent,15+,male,UNAIDS,"AIDSinfo Estimates 2026 (bulk CSV, Area Level ...",2026-08-24
1194,COG,Congo,2018,People living with HIV who have suppressed vir...,VIRAL_LOAD_SUPPRESSION,NaN,percent,15+,male,UNAIDS,"AIDSinfo Estimates 2026 (bulk CSV, Area Level ...",2026-08-24
1195,COG,Congo,2019,People living with HIV who have suppressed vir...,VIRAL_LOAD_SUPPRESSION,NaN,percent,15+,male,UNAIDS,"AIDSinfo Estimates 2026 (bulk CSV, Area Level ...",2026-08-24
1196,COG,Congo,2020,People living with HIV who have suppressed vir...,VIRAL_LOAD_SUPPRESSION,NaN,percent,15+,male,UNAIDS,"AIDSinfo Estimates 2026 (bulk CSV, Area Level ...",2026-08-24
1197,COG,Congo,2021,People living with HIV who have suppressed vir...,VIRAL_LOAD_SUPPRESSION,NaN,percent,15+,male,UNAIDS,"AIDSinfo Estimates 2026 (bulk CSV, Area Level ...",2026-08-24
1198,COG,Congo,2022,People living with HIV who have suppressed vir...,VIRAL_LOAD_SUPPRESSION,NaN,percent,15+,male,UNAIDS,"AIDSinfo Estimates 2026 (bulk CSV, Area Level ...",2026-08-24
1199,COG,Congo,2023,People living with HIV who have suppressed vir...,VIRAL_LOAD_SUPPRESSION,NaN,percent,15+,male,UNAIDS,"AIDSinfo Estimates 2026 (bulk CSV, Area Level ...",2026-08-24
1200,COG,Congo,2024,People living with HIV who have suppressed vir...,VIRAL_LOAD_SUPPRESSION,NaN,percent,15+,male,UNAIDS,"AIDSinfo Estimates 2026 (bulk CSV, Area Level ...",2026-08-24
1201,COG,Congo,2025,People living with HIV who have suppressed vir...,VIRAL_LOAD_SUPPRESSION,NaN,percent,15+,male,UNAIDS,"AIDSinfo Estimates 2026 (bulk CSV, Area Level ...",2026-08-24
1202,COG,Congo,2017,People living with HIV who have suppressed vir...,VIRAL_LOAD_SUPPRESSION,NaN,percent,all,both,UNAIDS,"AIDSinfo Estimates 2026 (bulk CSV, Area Level ...",2026-08-24
1203,COG,Congo,2018,People living with HIV who have suppressed vir...,VIRAL_LOAD_SUPPRESSION,NaN,percent,all,both,UNAIDS,"AIDSinfo Estimates 2026 (bulk CSV, Area Level ...",2026-08-24
1204,COG,Congo,2019,People living with HIV who have suppressed vir...,VIRAL_LOAD_SUPPRESSION,NaN,percent,all,both,UNAIDS,"AIDSinfo Estimates 2026 (bulk CSV, Area Level ...",2026-08-24
1205,COG,Congo,2020,People living with HIV who have suppressed vir...,VIRAL_LOAD_SUPPRESSION,NaN,percent,all,both,UNAIDS,"AIDSinfo Estimates 2026 (bulk CSV, Area Level ...",2026-08-24
1206,COG,Congo,2021,People living with HIV who have suppressed vir...,VIRAL_LOAD_SUPPRESSION,NaN,percent,all,both,UNAIDS,"AIDSinfo Estimates 2026 (bulk CSV, Area Level ...",2026-08-24
1207,COG,Congo,2022,People living with HIV who have suppressed vir...,VIRAL_LOAD_SUPPRESSION,NaN,percent,all,both,UNAIDS,"AIDSinfo Estimates 2026 (bulk CSV, Area Level ...",2026-08-24
1208,COG,Congo,2023,People living with HIV who have suppressed vir...,VIRAL_LOAD_SUPPRESSION,NaN,percent,all,both,UNAIDS,"AIDSinfo Estimates 2026 (bulk CSV, Area Level ...",2026-08-24
1209,COG,Congo,2024,People living with HIV who have suppressed vir...,VIRAL_LOAD_SUPPRESSION,NaN,percent,all,both,UNAIDS,"AIDSinfo Estimates 2026 (bulk CSV, Area Level ...",2026-08-24
1210,COG,Congo,2025,People living with HIV who have suppressed vir...,VIRAL_LOAD_SUPPRESSION,NaN,percent,all,both,UNAIDS,"AIDSinfo Estimates 2026 (bulk CSV, Area Level ...",2026-08-24

In [23]:
# suppression des valeurs manquantes
hiv_cog = hiv_cog.dropna()
hiv_cog.isnull().sum()

country_code      0
country_name      0
year              0
indicator         0
indicator_code    0
value             0
unit              0
age_group         0
sex               0
source_org        0
source_dataset    0
retrieval_date    0
dtype: int64

In [24]:
# Exportation du dataset de l'EDA
hiv_cog.to_csv("Donnees_congo.csv")

In [ ]:
# Assurons-nous simplement qu'elle est bien au format entier
hiv_cog['year'] = hiv_cog['year'].astype(int)

In [30]:
# ==============================================================================
# CRÉATION & CALCUL DES INDICATEURS
# ==============================================================================

# Prevalence
preva_df = hiv_cog[hiv_cog['indicator_code'].isin(['hiv_0000000001', 'anc_testing', 'hiv_prevalence', "hiv_0000000020", "hiv_0000000026", "mdg_0000000029", 'new_infections',"plwh", "sdghiv" ])]
preva_trend = testing_df.groupby('year')['value'].mean().reset_index()

# Dépistage & Diagnostic (Connaissance du statut sérologique)
testing_df = hiv_cog[hiv_cog['indicator_code'].isin(['hiv_statusknownhiv', 'anc_testing', 'number_plhiv_knowledge_of_status'])]
testing_trend = testing_df.groupby('year')['value'].mean().reset_index()

# Prise en charge médicale (Couverture ART / Antirétroviraux)
art_df = hiv_cog[hiv_cog['indicator_code'].isin(['percent_plwh', 'hiv_artcoverage']) & (hiv_cog['sex'] == 'both')]
art_trend = art_df.groupby('year')['value'].mean().reset_index()

# Incidence du VIH (Nouveaux cas)
incidence_df = hiv_cog[hiv_cog['indicator_code'].isin(['new_infections', 'hiv_0000000026']) & (hiv_cog['sex'] == 'both')]
incidence_trend = incidence_df.groupby('year')['value'].sum().reset_index()

# Impact sur la mortalité (Décès liés au SIDA)
deaths_df = hiv_cog[hiv_cog['indicator_code'].isin(['aids_deaths', 'hiv_0000000006']) & (hiv_cog['sex'] == 'both')]
deaths_trend = deaths_df.groupby('year')['value'].sum().reset_index()

# predominance de Genre (Hommes vs Femmes) de 1990 à 2025 analyse basée sur les données de l'ONUSIDA & l'OMS
gender_df = hiv_cog[hiv_cog['indicator_code'].isin(['hiv_0000000001', 'plwh']) & hiv_cog['sex'].isin(['male', 'female'])]
gender_trend = gender_df.groupby(['year', 'sex'])['value'].sum().reset_index()

# Structure par tranche d'âge
age_df = hiv_cog[hiv_cog['indicator_code'].isin(['plwh', 'new_infections']) & ~hiv_cog['age_group'].isin(['all', '0-14', "15-24","15-49"])]
age_trend = age_df.groupby(['year', 'age_group'])['value'].sum().reset_index()

print("✓ Tous les indicateurs clés (KPIs) ont été créés et agrégés avec succès.")

✓ Tous les indicateurs clés (KPIs) ont été créés et agrégés avec succès.